Repository moosehandlr/monster_shop_2005, pull requests merged in 2020-09, with the labels that each got.

#26 User registration
  Gemfile
  Gemfile.lock
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/layouts/application.html.erb
  app/views/users/new.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  db/migrate/20200908233406_create_users.rb
  db/schema.rb
  spec/features/users/new_spec.rb
  spec/models/user_spec.rb
Labels: Author Resolves Line Comments, Author thinks ready to merge, Peer Coded Together, enhancement

#28 US 13-16 Completed
  app/controllers/admin/base_controller.rb
  app/controllers/admin/dashboard_controller.rb
  app/controllers/application_controller.rb
  app/controllers/merchant/base_controller.rb
  app/controllers/merchant/dashboard_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/admin/dashboard/index.html.erb
  app/views/layouts/application.html.erb
  app/views/merchant/dashboard/index.html.erb
  app/views/sessions/new.html.erb
  config/routes.rb
  db/migrate/20200909184131_add_role_to_users.rb
  db/schema.rb
  spec/features/sessions/delete_spec.rb
  spec/features/sessions/new_spec.rb
Labels: enhancement

#29 Navigation User Stories
  app/controllers/cart_controller.rb
  app/controllers/sessions_controller.rb
  app/views/layouts/application.html.erb
  config/routes.rb
  spec/features/navigation/admin_spec.rb
  spec/features/navigation/merchant_spec.rb
  spec/features/navigation/user_spec.rb
  spec/features/navigation/visitor_spec.rb
  spec/features/sessions/new_spec.rb
Labels: Peer Coded Together, Reviewer Merges

#30 Items
  app/controllers/application_controller.rb
  app/controllers/items_controller.rb
  app/controllers/orders_controller.rb
  app/models/item.rb
  app/views/items/index.html.erb
  app/views/layouts/application.html.erb
  db/migrate/20200910163447_add_quantity_purchased_to_items.rb
  db/schema.rb
  spec/features/items/index_spec.rb
  spec/features/items/merchant_items_index_spec.rb
  spec/features/items/new_spec.rb
  spec/features/orders/creation_spec.rb
  spec/models/item_spec.rb
Labels: Reviewer Adds Line Comments, Reviewer Merges, Reviewer Resolves Line Comments, Reviewer Thinks Ready To Merge, enhancement

#31 User profile
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/users/_form.html.erb
  app/views/users/edit.html.erb
  app/views/users/new.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  db/seeds.rb
  spec/features/users/edit_spec.rb
  spec/features/users/show_spec.rb
  spec/models/user_spec.rb
Labels: new feature

#32 Shopping cart
  app/controllers/application_controller.rb
  app/controllers/cart_controller.rb
  app/controllers/orders_controller.rb
  app/controllers/user/base_controller.rb
  app/controllers/user/orders_controller.rb
  app/controllers/users_controller.rb
  app/models/order.rb
  app/models/user.rb
  app/views/cart/show.html.erb
  app/views/user/orders/index.html.erb
  app/views/user/orders/show.html.erb
  app/views/users/index.html.erb
  config/routes.rb
  db/migrate/20200911225130_add_order_status_to_orders.rb
  db/migrate/20200911225910_add_users_to_order.rb
  db/schema.rb
  db/seeds.rb
  spec/features/cart/checkout_spec.rb
  spec/features/cart/show_spec.rb
  spec/features/items/destroy_spec.rb
  spec/features/merchants/destroy_spec.rb
  spec/features/merchants/statistics_spec.rb
  spec/features/orders/creation_spec.rb
  spec/features/orders/new_spec.rb
  spec/models/item_orders_spec.rb
  spec/models/item_spec.rb
  spec/models/merchant_spec.rb
  spec/models/order_spec.rb
  spec/models/user_spec.rb
Labels: new feature

#42 User orders complete. User Stories 27-33
  app/controllers/admin/dashboard_controller.rb
  app/controllers/admin/orders_controller.rb
  app/controllers/admin/users_controller.rb
  app/controllers/user/orders_controller.rb
  app/models/item.rb
  app/models/order.rb
  app/views/admin/dashboard/index.html.erb
  app/views/admin/users/show.html.erb
  app/views/layouts/application.html.erb
  app/views/user/orders/index.html.erb
  app/views/user/orders/show.html.erb
  config/routes.rb
  db/migrate/20200912184804_add_order_status_to_item_orders.rb
  db/schema.rb
  db/seeds.rb
  spec/features/admins/index_spec.rb
  spec/features/merchants/statistics_spec.rb
  spec/features/navigation_spec.rb
  spec/features/orders/creation_spec.rb
  spec/features/users/new_spec.rb
  spec/features/users/orders/index_spec.rb
  spec/features/users/orders/show_spec.rb
  spec/models/item_spec.rb
  spec/models/order_spec.rb
Labels: Author needs review, Author thinks ready to merge, Peer Coded Together

#71 User management
  app/assets/stylesheets/application.css
  app/controllers/admin/users_controller.rb
  app/controllers/welcome_controller.rb
  app/views/admin/merchants/index.html.erb
  app/views/admin/users/index.html.erb
  app/views/admin/users/show.html.erb
  app/views/welcome/index.html.erb
  config/routes.rb
  spec/features/admins/merchants/index_spec.rb
  spec/features/admins/users/index_spec.rb
  spec/features/admins/users/show_spec.rb
Labels: Author thinks ready to merge, Peer Coded Together, Reviewer Merges, new feature

#73 Merchant items
  app/controllers/merchant/items_controller.rb
  app/models/item.rb
  app/views/merchant/items/edit.html.erb
  app/views/merchant/items/index.html.erb
  app/views/merchant/items/new.html.erb
  config/routes.rb
  db/seeds.rb
  spec/features/items/edit_spec.rb
  spec/features/items/new_spec.rb
  spec/features/merchant_users/items/edit_spec.rb
  spec/features/merchant_users/items/index_spec.rb
  spec/models/item_spec.rb
Labels: Peer Coded Together, Reviewer Merges
